// Custom API types (not generated by Prisma)
export interface ElevenLabsWebhookRequest {
  function_name: string;
  parameters: Record<string, any>;
  conversation_id: string;
}

export interface ElevenLabsWebhookResponse {
  success: boolean;
  message: string;
  data?: any;
  error?: string;
}

// Simplified interface for initial user creation during onboarding
export interface BasicInfo {
  fullName: string;
  conversationID: string;
}
